"""add nuevos modulos company

Revision ID: 0e5562dc7261
Revises: bba8ad8d98a8
Create Date: 2026-09-09 19:31:05.939212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5562dc7261'
down_revision: Union[str, None] = 'bba8ad8d98a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_type', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('actividad_economica', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'actividad_economica')
    op.drop_column('companies', 'company_type')
    # ### end Alembic commands ###
