"""nuevos campos 

Revision ID: 19344eaf55f6
Revises: 77ec23beebef
Create Date: 2026-08-26 21:46:19.437775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19344eaf55f6'
down_revision: Union[str, None] = '77ec23beebef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_positions', sa.Column('department', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_positions', 'department')
    # ### end Alembic commands ###
