"""add nuevos campos companie y organizacion

Revision ID: 211fccd70f95
Revises: c0339edafa6f
Create Date: 2026-07-20 22:04:19.504181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211fccd70f95'
down_revision: Union[str, None] = 'c0339edafa6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('show_on_website', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_column('organizations', 'slug')
    op.drop_column('companies', 'show_on_website')
    # ### end Alembic commands ###
