"""add company_signers and inspection nomenclatura

Revision ID: 273f07a82ff1
Revises: e04b4f1444de
Create Date: 2026-06-26 09:17:52.486864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273f07a82ff1'
down_revision: Union[str, None] = 'e04b4f1444de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_signers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('elaborated_by', sa.String(length=150), nullable=True),
    sa.Column('elaborated_role', sa.String(length=100), nullable=True),
    sa.Column('reviewed_by', sa.String(length=150), nullable=True),
    sa.Column('reviewed_role', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=150), nullable=True),
    sa.Column('approved_role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_index(op.f('ix_company_signers_id'), 'company_signers', ['id'], unique=False)
    op.add_column('inspection_types', sa.Column('nomenclatura', sa.String(length=50), nullable=True))
    op.add_column('inspection_types', sa.Column('correlativo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection_types', 'correlativo')
    op.drop_column('inspection_types', 'nomenclatura')
    op.drop_index(op.f('ix_company_signers_id'), table_name='company_signers')
    op.drop_table('company_signers')
    # ### end Alembic commands ###
