"""add_inspection_templates

Revision ID: 2d9057c191b3
Revises: 845614bd45a2
Create Date: 2026-07-23 11:55:33.437012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9057c191b3'
down_revision: Union[str, None] = '845614bd45a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('structure_type', sa.Enum('FORMULARIO', 'MATRIZ', 'FORMULARIO_MATRIZ', name='structure_type_enum'), nullable=False),
    sa.Column('source', sa.Enum('GLOBAL', 'ORGANIZACION', name='template_source_enum'), nullable=False),
    sa.Column('suggested_periodicity', sa.String(length=20), nullable=True),
    sa.Column('suggested_pdf_template', sa.String(length=50), nullable=True),
    sa.Column('fields_schema', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('copied_from_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['copied_from_id'], ['inspection_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_templates_id'), 'inspection_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspection_templates_id'), table_name='inspection_templates')
    op.drop_table('inspection_templates')
    # ### end Alembic commands ###
