"""add_firmas_organizacion

Revision ID: 2fbd83c98197
Revises: bef5cb9cc94b
Create Date: 2026-08-11 21:41:25.233552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbd83c98197'
down_revision: Union[str, None] = 'bef5cb9cc94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('elaborated_role', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('reviewed_by', sa.String(length=150), nullable=True))
    op.add_column('organizations', sa.Column('reviewed_role', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('approved_by', sa.String(length=150), nullable=True))
    op.add_column('organizations', sa.Column('approved_role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'approved_role')
    op.drop_column('organizations', 'approved_by')
    op.drop_column('organizations', 'reviewed_role')
    op.drop_column('organizations', 'reviewed_by')
    op.drop_column('organizations', 'elaborated_role')
    # ### end Alembic commands ###
