"""add company_signers and inspection nomenclatura

Revision ID: 38b9d119781f
Revises: 273f07a82ff1
Create Date: 2026-06-26 12:14:06.842843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b9d119781f'
down_revision: Union[str, None] = '273f07a82ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_types', 'correlativo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_types', 'correlativo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
