"""add company_signers and inspection nomenclatura

Revision ID: 512cef1cbe56
Revises: 38b9d119781f
Create Date: 2026-06-28 12:31:31.251106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512cef1cbe56'
down_revision: Union[str, None] = '38b9d119781f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_types', 'correlativo',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inspection_types', 'correlativo',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
