"""add rsponsable_name en inspecciones

Revision ID: 54c902358cc0
Revises: 8edc03287d45
Create Date: 2026-07-08 16:49:22.602931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c902358cc0'
down_revision: Union[str, None] = '8edc03287d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corrective_actions', sa.Column('responsible_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corrective_actions', 'responsible_name')
    # ### end Alembic commands ###
