"""nuevo campos en geritra

Revision ID: 77ec23beebef
Revises: 8b1e7466317e
Create Date: 2026-08-21 18:55:14.854058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ec23beebef'
down_revision: Union[str, None] = '8b1e7466317e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_matrix_rows', sa.Column('risk_type', sa.String(length=50), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('health_effects', sa.Text(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('health_surveillance', sa.Text(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('control_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('improvement_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_matrix_rows', 'improvement_notes')
    op.drop_column('risk_matrix_rows', 'control_date')
    op.drop_column('risk_matrix_rows', 'health_surveillance')
    op.drop_column('risk_matrix_rows', 'health_effects')
    op.drop_column('risk_matrix_rows', 'risk_type')
    # ### end Alembic commands ###
