"""inspection_structure_type_scope_general_data

Revision ID: 845614bd45a2
Revises: 211fccd70f95
Create Date: 2026-07-21 20:48:04.541853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845614bd45a2'
down_revision: Union[str, None] = '211fccd70f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
