"""add sequence

Revision ID: 8470ae4402fd
Revises: b5ac4232a0c8
Create Date: 2026-06-30 23:37:16.124039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8470ae4402fd'
down_revision: Union[str, None] = 'b5ac4232a0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequences_id'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_sequence_templates_id'), table_name='sequence_templates')
    op.drop_table('sequence_templates')
    op.drop_column('inspection_types', 'correlativo')
    op.drop_column('inspection_types', 'nomenclatura')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_types', sa.Column('nomenclatura', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('inspection_types', sa.Column('correlativo', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('sequence_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_prefix', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('default_padding', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('default_suffix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sequence_templates_pkey')),
    sa.UniqueConstraint('code', name=op.f('sequence_templates_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sequence_templates_id'), 'sequence_templates', ['id'], unique=False)
    op.create_table('sequences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('suffix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('padding', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('next_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('sequences_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['sequence_templates.id'], name=op.f('sequences_template_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('sequences_pkey')),
    sa.UniqueConstraint('company_id', 'template_id', name=op.f('uq_sequence_company_template'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sequences_id'), 'sequences', ['id'], unique=False)
    # ### end Alembic commands ###
