"""nueva alertas

Revision ID: 8b1e7466317e
Revises: 2fbd83c98197
Create Date: 2026-08-17 16:28:00.285031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b1e7466317e'
down_revision: Union[str, None] = '2fbd83c98197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_alert_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('days_before', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_alert_configs_id'), 'document_alert_configs', ['id'], unique=False)
    op.create_index(op.f('ix_document_alert_configs_organization_id'), 'document_alert_configs', ['organization_id'], unique=True)
    op.create_table('document_alert_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('company_document_id', sa.Integer(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('sent_to_email', sa.String(length=200), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_document_id'], ['company_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['config_id'], ['document_alert_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_document_id', 'days_before', name='uq_alert_log_doc_days')
    )
    op.create_index(op.f('ix_document_alert_logs_company_document_id'), 'document_alert_logs', ['company_document_id'], unique=False)
    op.create_index(op.f('ix_document_alert_logs_config_id'), 'document_alert_logs', ['config_id'], unique=False)
    op.create_index(op.f('ix_document_alert_logs_id'), 'document_alert_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_alert_logs_id'), table_name='document_alert_logs')
    op.drop_index(op.f('ix_document_alert_logs_config_id'), table_name='document_alert_logs')
    op.drop_index(op.f('ix_document_alert_logs_company_document_id'), table_name='document_alert_logs')
    op.drop_table('document_alert_logs')
    op.drop_index(op.f('ix_document_alert_configs_organization_id'), table_name='document_alert_configs')
    op.drop_index(op.f('ix_document_alert_configs_id'), table_name='document_alert_configs')
    op.drop_table('document_alert_configs')
    # ### end Alembic commands ###
