"""add company code

Revision ID: 8edc03287d45
Revises: 4af50c2168f8
Create Date: 2026-07-04 14:10:01.279716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8edc03287d45'
down_revision: Union[str, None] = '4af50c2168f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_code', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'companies', ['company_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'company_code')
    # ### end Alembic commands ###
