"""add sequence_new

Revision ID: b0675f9aa206
Revises: 8470ae4402fd
Create Date: 2026-07-03 20:48:44.548854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0675f9aa206'
down_revision: Union[str, None] = '8470ae4402fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('template', sa.String(length=255), nullable=False),
    sa.Column('padding', sa.Integer(), nullable=False),
    sa.Column('increment', sa.Integer(), nullable=False),
    sa.Column('reset_policy', sa.Enum('NEVER', 'YEARLY', 'MONTHLY', name='reset_policy_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_definitions_code'), 'sequence_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_sequence_definitions_id'), 'sequence_definitions', ['id'], unique=False)
    op.create_table('sequence_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_def_id', sa.Integer(), nullable=False),
    sa.Column('scope_key', sa.String(length=500), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('reset_at', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sequence_def_id'], ['sequence_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_def_id', 'scope_key', name='uq_counter_def_scope')
    )
    op.create_index(op.f('ix_sequence_counters_id'), 'sequence_counters', ['id'], unique=False)
    op.create_index(op.f('ix_sequence_counters_sequence_def_id'), 'sequence_counters', ['sequence_def_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequence_counters_sequence_def_id'), table_name='sequence_counters')
    op.drop_index(op.f('ix_sequence_counters_id'), table_name='sequence_counters')
    op.drop_table('sequence_counters')
    op.drop_index(op.f('ix_sequence_definitions_id'), table_name='sequence_definitions')
    op.drop_index(op.f('ix_sequence_definitions_code'), table_name='sequence_definitions')
    op.drop_table('sequence_definitions')
    # ### end Alembic commands ###
