"""add sequence global y local

Revision ID: b5ac4232a0c8
Revises: 2d70b26bf077
Create Date: 2026-06-28 22:38:48.271421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ac4232a0c8'
down_revision: Union[str, None] = '2d70b26bf077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sequence_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_prefix', sa.String(length=50), nullable=True),
    sa.Column('default_padding', sa.Integer(), nullable=False),
    sa.Column('default_suffix', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_sequence_templates_id'), 'sequence_templates', ['id'], unique=False)
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=50), nullable=True),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('padding', sa.Integer(), nullable=False),
    sa.Column('next_num', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['sequence_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'template_id', name='uq_sequence_company_template')
    )
    op.create_index(op.f('ix_sequences_id'), 'sequences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequences_id'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_sequence_templates_id'), table_name='sequence_templates')
    op.drop_table('sequence_templates')
    # ### end Alembic commands ###
