"""add modulo geritra

Revision ID: b7aa1469d98b
Revises: 54c902358cc0
Create Date: 2026-07-15 11:37:21.866004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7aa1469d98b'
down_revision: Union[str, None] = '54c902358cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_risk_category_org_name')
    )
    op.create_index(op.f('ix_risk_categories_id'), 'risk_categories', ['id'], unique=False)
    op.create_index(op.f('ix_risk_categories_organization_id'), 'risk_categories', ['organization_id'], unique=False)
    op.create_table('job_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('process', sa.String(length=150), nullable=True),
    sa.Column('num_workers', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_positions_company_id'), 'job_positions', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_positions_id'), 'job_positions', ['id'], unique=False)
    op.create_index(op.f('ix_job_positions_organization_id'), 'job_positions', ['organization_id'], unique=False)
    op.create_table('risk_factor_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('effect', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['risk_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_factor_catalog_category_id'), 'risk_factor_catalog', ['category_id'], unique=False)
    op.create_index(op.f('ix_risk_factor_catalog_id'), 'risk_factor_catalog', ['id'], unique=False)
    op.create_index(op.f('ix_risk_factor_catalog_organization_id'), 'risk_factor_catalog', ['organization_id'], unique=False)
    op.create_table('risk_matrices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_position_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('BORRADOR', 'ACTIVA', 'REVISION', 'ARCHIVADA', name='matrix_status_enum'), nullable=False),
    sa.Column('elaborated_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('elaborated_role', sa.String(length=100), nullable=True),
    sa.Column('reviewed_role', sa.String(length=100), nullable=True),
    sa.Column('approved_role', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_matrices_company_id'), 'risk_matrices', ['company_id'], unique=False)
    op.create_index(op.f('ix_risk_matrices_id'), 'risk_matrices', ['id'], unique=False)
    op.create_index(op.f('ix_risk_matrices_job_position_id'), 'risk_matrices', ['job_position_id'], unique=False)
    op.create_index(op.f('ix_risk_matrices_organization_id'), 'risk_matrices', ['organization_id'], unique=False)
    op.create_table('risk_matrix_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('factor_id', sa.Integer(), nullable=True),
    sa.Column('peligro', sa.String(length=300), nullable=False),
    sa.Column('efecto', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.Integer(), nullable=True),
    sa.Column('ic', sa.Integer(), nullable=True),
    sa.Column('ice', sa.Integer(), nullable=True),
    sa.Column('ie', sa.Integer(), nullable=True),
    sa.Column('consecuencia', sa.Integer(), nullable=True),
    sa.Column('probabilidad', sa.Integer(), nullable=True),
    sa.Column('estimacion', sa.Integer(), nullable=True),
    sa.Column('nivel_riesgo', sa.Enum('TRIVIAL', 'TOLERABLE', 'MODERADO', 'IMPORTANTE', 'INTOLERABLE', name='risk_level_enum'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['risk_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['factor_id'], ['risk_factor_catalog.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matrix_id'], ['risk_matrices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_matrix_rows_id'), 'risk_matrix_rows', ['id'], unique=False)
    op.create_index(op.f('ix_risk_matrix_rows_matrix_id'), 'risk_matrix_rows', ['matrix_id'], unique=False)
    op.create_table('risk_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('matrix_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsible_name', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'VENCIDA', name='risk_action_status_enum'), nullable=False),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['risk_matrices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['row_id'], ['risk_matrix_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_actions_id'), 'risk_actions', ['id'], unique=False)
    op.create_index(op.f('ix_risk_actions_matrix_id'), 'risk_actions', ['matrix_id'], unique=False)
    op.create_index(op.f('ix_risk_actions_row_id'), 'risk_actions', ['row_id'], unique=False)
    op.create_table('risk_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('control_type', sa.Enum('ELIMINACION', 'SUSTITUCION', 'INGENIERIA', 'ADMINISTRATIVO', 'EPP', name='control_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['row_id'], ['risk_matrix_rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_controls_id'), 'risk_controls', ['id'], unique=False)
    op.create_index(op.f('ix_risk_controls_row_id'), 'risk_controls', ['row_id'], unique=False)
    op.add_column('companies', sa.Column('geritra_config', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('companies_company_code_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_company_code'), 'companies', ['company_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_code'), table_name='companies')
    op.create_unique_constraint(op.f('companies_company_code_key'), 'companies', ['company_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('companies', 'geritra_config')
    op.drop_index(op.f('ix_risk_controls_row_id'), table_name='risk_controls')
    op.drop_index(op.f('ix_risk_controls_id'), table_name='risk_controls')
    op.drop_table('risk_controls')
    op.drop_index(op.f('ix_risk_actions_row_id'), table_name='risk_actions')
    op.drop_index(op.f('ix_risk_actions_matrix_id'), table_name='risk_actions')
    op.drop_index(op.f('ix_risk_actions_id'), table_name='risk_actions')
    op.drop_table('risk_actions')
    op.drop_index(op.f('ix_risk_matrix_rows_matrix_id'), table_name='risk_matrix_rows')
    op.drop_index(op.f('ix_risk_matrix_rows_id'), table_name='risk_matrix_rows')
    op.drop_table('risk_matrix_rows')
    op.drop_index(op.f('ix_risk_matrices_organization_id'), table_name='risk_matrices')
    op.drop_index(op.f('ix_risk_matrices_job_position_id'), table_name='risk_matrices')
    op.drop_index(op.f('ix_risk_matrices_id'), table_name='risk_matrices')
    op.drop_index(op.f('ix_risk_matrices_company_id'), table_name='risk_matrices')
    op.drop_table('risk_matrices')
    op.drop_index(op.f('ix_risk_factor_catalog_organization_id'), table_name='risk_factor_catalog')
    op.drop_index(op.f('ix_risk_factor_catalog_id'), table_name='risk_factor_catalog')
    op.drop_index(op.f('ix_risk_factor_catalog_category_id'), table_name='risk_factor_catalog')
    op.drop_table('risk_factor_catalog')
    op.drop_index(op.f('ix_job_positions_organization_id'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_id'), table_name='job_positions')
    op.drop_index(op.f('ix_job_positions_company_id'), table_name='job_positions')
    op.drop_table('job_positions')
    op.drop_index(op.f('ix_risk_categories_organization_id'), table_name='risk_categories')
    op.drop_index(op.f('ix_risk_categories_id'), table_name='risk_categories')
    op.drop_table('risk_categories')
    # ### end Alembic commands ###
