"""add_worker

Revision ID: bba8ad8d98a8
Revises: 6e6fc8959c1b
Create Date: 2026-09-04 19:37:42.582995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba8ad8d98a8'
down_revision: Union[str, None] = '6e6fc8959c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=True),
    sa.Column('doc_type', sa.Enum('CEDULA', 'PASAPORTE', 'OTRO', name='doc_type_enum'), nullable=False),
    sa.Column('doc_number', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MASCULINO', 'FEMENINO', 'OTRO', name='gender_enum'), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('contract_type', sa.Enum('INDEFINIDO', 'PLAZO_FIJO', 'OBRA', 'SERVICIOS', 'PASANTIA', 'OTRO', name='contract_type_enum'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVO', 'INACTIVO', 'SUSPENDIDO', 'RETIRADO', name='worker_status_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('job_position_id', sa.Integer(), nullable=True),
    sa.Column('disability_type', sa.String(length=100), nullable=True),
    sa.Column('disability_pct', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'doc_type', 'doc_number', name='uq_worker_company_document')
    )
    op.create_index(op.f('ix_workers_company_id'), 'workers', ['company_id'], unique=False)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    op.create_index(op.f('ix_workers_job_position_id'), 'workers', ['job_position_id'], unique=False)
    op.create_table('worker_position_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('job_position_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worker_position_history_id'), 'worker_position_history', ['id'], unique=False)
    op.create_index(op.f('ix_worker_position_history_worker_id'), 'worker_position_history', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_position_history_worker_id'), table_name='worker_position_history')
    op.drop_index(op.f('ix_worker_position_history_id'), table_name='worker_position_history')
    op.drop_table('worker_position_history')
    op.drop_index(op.f('ix_workers_job_position_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_company_id'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
