"""add_gestuin documental

Revision ID: bef5cb9cc94b
Revises: d91274c43209
Create Date: 2026-08-03 19:55:27.614794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef5cb9cc94b'
down_revision: Union[str, None] = 'd91274c43209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_custom_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('BORRADOR', 'VIGENTE', 'ARCHIVADO', name='custom_doc_status_enum'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_custom_documents_id'), 'company_custom_documents', ['id'], unique=False)
    op.create_table('document_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_document_id', sa.Integer(), nullable=True),
    sa.Column('custom_document_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.Enum('PRINCIPAL', 'VERSION', 'ADJUNTO', 'EVIDENCIA', name='document_file_type_enum'), nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_document_id'], ['company_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_document_id'], ['company_custom_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_files_id'), 'document_files', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_files_id'), table_name='document_files')
    op.drop_table('document_files')
    op.drop_index(op.f('ix_company_custom_documents_id'), table_name='company_custom_documents')
    op.drop_table('company_custom_documents')
    # ### end Alembic commands ###
