"""add modulo geritra

Revision ID: c0339edafa6f
Revises: b7aa1469d98b
Create Date: 2026-07-19 09:03:07.450488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0339edafa6f'
down_revision: Union[str, None] = 'b7aa1469d98b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_positions', sa.Column('has_disability', sa.Boolean(), nullable=True))
    op.add_column('job_positions', sa.Column('disability_pct', sa.Integer(), nullable=True))
    op.add_column('job_positions', sa.Column('routine_activity', sa.Text(), nullable=True))
    op.add_column('job_positions', sa.Column('non_routine_activity', sa.Text(), nullable=True))
    op.add_column('job_positions', sa.Column('machinery', sa.Text(), nullable=True))
    op.add_column('job_positions', sa.Column('technical_aids', sa.Text(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('res_ip', sa.Integer(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('res_ic', sa.Integer(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('res_ice', sa.Integer(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('res_ie', sa.Integer(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('res_consecuencia', sa.Integer(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('res_probabilidad', sa.Integer(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('res_estimacion', sa.Integer(), nullable=True))
    op.add_column('risk_matrix_rows', sa.Column('res_nivel_riesgo', sa.Enum('TRIVIAL', 'TOLERABLE', 'MODERADO', 'IMPORTANTE', 'INTOLERABLE', name='risk_level_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_matrix_rows', 'res_nivel_riesgo')
    op.drop_column('risk_matrix_rows', 'res_estimacion')
    op.drop_column('risk_matrix_rows', 'res_probabilidad')
    op.drop_column('risk_matrix_rows', 'res_consecuencia')
    op.drop_column('risk_matrix_rows', 'res_ie')
    op.drop_column('risk_matrix_rows', 'res_ice')
    op.drop_column('risk_matrix_rows', 'res_ic')
    op.drop_column('risk_matrix_rows', 'res_ip')
    op.drop_column('job_positions', 'technical_aids')
    op.drop_column('job_positions', 'machinery')
    op.drop_column('job_positions', 'non_routine_activity')
    op.drop_column('job_positions', 'routine_activity')
    op.drop_column('job_positions', 'disability_pct')
    op.drop_column('job_positions', 'has_disability')
    # ### end Alembic commands ###
