"""add pdf_template to inspection_types

Revision ID: c749fd3e1ac1
Revises: e087bc40dfee
Create Date: 2026-06-23 22:38:14.000450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c749fd3e1ac1'
down_revision: Union[str, None] = 'e087bc40dfee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
