"""add photo_path to records and foto field type

Revision ID: cb0f2fd3f3d1
Revises: c749fd3e1ac1
Create Date: 2026-06-24 16:16:12.715404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0f2fd3f3d1'
down_revision: Union[str, None] = 'c749fd3e1ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
