"""add diagnostics

Revision ID: d26a8868e46e
Revises: 5a8a54490be3
Create Date: 2026-06-17 10:44:46.587609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26a8868e46e'
down_revision: Union[str, None] = '5a8a54490be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('inspection_number', sa.String(length=50), nullable=True),
    sa.Column('diagnostic_type', sa.Enum('INSPECCION', 'REINSPECCION', name='diagnostic_type_enum'), nullable=False),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('BORRADOR', 'COMPLETADO', name='diagnostic_status_enum'), nullable=False),
    sa.Column('company_type', sa.String(length=20), nullable=True),
    sa.Column('employer_name', sa.String(length=200), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('ruc', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('economic_activity', sa.String(length=200), nullable=True),
    sa.Column('workplace_type', sa.String(length=20), nullable=True),
    sa.Column('workplace_address', sa.String(length=255), nullable=True),
    sa.Column('workplace_count', sa.Integer(), nullable=True),
    sa.Column('work_schedule', sa.String(length=50), nullable=True),
    sa.Column('total_workers', sa.Integer(), nullable=True),
    sa.Column('iess_payroll', sa.Boolean(), nullable=True),
    sa.Column('workers_male', sa.Integer(), nullable=True),
    sa.Column('workers_female', sa.Integer(), nullable=True),
    sa.Column('workers_remote', sa.Integer(), nullable=True),
    sa.Column('workers_foreign', sa.Integer(), nullable=True),
    sa.Column('workers_teen', sa.Integer(), nullable=True),
    sa.Column('workers_pregnant', sa.Integer(), nullable=True),
    sa.Column('workers_senior', sa.Integer(), nullable=True),
    sa.Column('workers_child', sa.Integer(), nullable=True),
    sa.Column('workers_nursing', sa.Integer(), nullable=True),
    sa.Column('interviewed', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostics_id'), 'diagnostics', ['id'], unique=False)
    op.create_table('diagnostic_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnostic_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=10), nullable=False),
    sa.Column('answer', sa.Enum('CUMPLE', 'NO_CUMPLE', 'NO_APLICA', name='answer_value_enum'), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['diagnostic_id'], ['diagnostics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_answers_id'), 'diagnostic_answers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnostic_answers_id'), table_name='diagnostic_answers')
    op.drop_table('diagnostic_answers')
    op.drop_index(op.f('ix_diagnostics_id'), table_name='diagnostics')
    op.drop_table('diagnostics')
    # ### end Alembic commands ###
