"""add company description fields

Revision ID: d8a83b34b891
Revises: 257b8df12bd9
Create Date: 2026-06-22 19:01:07.337183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a83b34b891'
down_revision: Union[str, None] = '257b8df12bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('intro_inspeccion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'intro_inspeccion')
    op.drop_column('companies', 'descripcion')
    # ### end Alembic commands ###
