"""add photo_path to records and foto field type

Revision ID: e04b4f1444de
Revises: cb0f2fd3f3d1
Create Date: 2026-06-24 16:23:10.458346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04b4f1444de'
down_revision: Union[str, None] = 'cb0f2fd3f3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_records', sa.Column('photo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection_records', 'photo_path')
    # ### end Alembic commands ###
