"""add company description fields

Revision ID: e087bc40dfee
Revises: d8a83b34b891
Create Date: 2026-06-23 09:33:00.825270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e087bc40dfee'
down_revision: Union[str, None] = 'd8a83b34b891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspection_types', sa.Column('pdf_template', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspection_types', 'pdf_template')
    # ### end Alembic commands ###
